- index.html
Hello,  just adding an h1  for my first open source pull request.
> adding h1 to index.html

- Contributors.md
- index.html
- style.css
Hey guys, I'm adding a css file and a waste input hope you all will like it. :)
Thank you
>  adding style.css and a waste input

- index.html
- style.css
I've added Bootstrap integration. Added a drop-down menu. And replaced the custom button with bootstrap buttons. have created a signup button that can be used to redirect to a signup form. Check Out!
> Added Bootstarp and Revamped the homepage.

- Contributors.md
> I would like to contribute to this project

- React_files/src/App.js
- React_files/src/Card.js
- React_files/src/resultBox.js
I hope everyone will like the submit button
> Adding a submit button

- React_files/src/App.css
- React_files/src/App.js
- React_files/src/Card.js
- React_files/src/Score.js
- React_files/src/resultBox.js
Adding some new feature hope everyone will like it. :)
> Adding a Score window compliting the project as a app.

- React_files/src/components/Score/Score.js
> Made changes to Score Logic

- Contributors.md
Just adding my name to the list
> Added simonp9999 to Contributors list

- Contributors.md
> add ShaniBel to the contributors list

- Contributors.md
Added myself in contributors.Kindly let me in.
> Added data contributors file

- Contributors.md
- React_files/src/components/Score/Score.js
- React_files/src/components/Trash/Trash.js
- React_files/src/containers/App.css
Hey, this is my first pull request! As said in the title, I mostly touched the CSS as I'm still a beginner in React. Hope you'll like it!
> Added myself to contributors, tweaked up the CSS and did minor code cleanups

- Contributors.md
Added my name to the list. Please let me in. :)
> new contributor

- style.css
A minor change to practice working with GitHub on open source projects. Please review.
> Added color gradient to the background

- Contributors.md
Hi, just added my name to the list of contributers
> Adding myself onto list of contributors

- Contributors.md
Added my name to the Contributors list. Looking forward to contributing to the Recycling Tracker.
> Add LichtZinnig to Contributors list

- React_files/public/index.html
Updated the title from "React App" to "Recycling Tracker"
> Updated the title

- Contributors.md
I've just added my info to the list. Please let me in, this is my first time.
> please let me in, this is my first time

- Contributors.md
Hello! 
I added my name to the Contributors list. I will check out the code and look at the issues tab to see where I can help. If there is anything you need immediate assistance with then please let me know!
> Added name to Contributors list

- Contributors.md
Added my name to contributors list.Please accept my request.
> Added my name to contributors list

- Contributors.md
I've added my name to the list. @Romson @waqar3
> Added my name to the contributor list

- Contributors.md
- React_files/src/registerServiceWorker.js
I've added my name to the list. @Romson
> added my name to the contributor list and added comment to js file

- Contributors.md
Added my Name to the Projectlist
> added @Wolfslicht to constributionlist
